import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface EnrollmentData {
  fullName: string;
  email: string;
  mobile: string;
  dob: string;
  gender: string;
  qualification: string;
  city: string;
  state: string;
  country: string;
  address: string;
  workingInSolar: boolean;
  referralCode?: string;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { enrollmentData } = await req.json() as { enrollmentData: EnrollmentData };

    console.log('Creating payment for enrollment:', enrollmentData);

    // Initialize Supabase client
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Create enrollment record
    const { data: enrollment, error: enrollmentError } = await supabase
      .from('enrollments')
      .insert({
        enrollment_id: '', // Will be auto-generated by trigger
        full_name: enrollmentData.fullName,
        email: enrollmentData.email,
        mobile: enrollmentData.mobile,
        dob: enrollmentData.dob,
        gender: enrollmentData.gender,
        qualification: enrollmentData.qualification,
        city: enrollmentData.city,
        state: enrollmentData.state,
        country: enrollmentData.country,
        address: enrollmentData.address,
        working_in_solar: enrollmentData.workingInSolar,
        referral_code: enrollmentData.referralCode || null,
        payment_status: 'pending',
      })
      .select()
      .single();

    if (enrollmentError) {
      console.error('Error creating enrollment:', enrollmentError);
      throw enrollmentError;
    }

    console.log('Enrollment created:', enrollment);

    // Cashfree API credentials
    const cashfreeAppId = Deno.env.get('CASHFREE_APP_ID');
    const cashfreeSecretKey = Deno.env.get('CASHFREE_SECRET_KEY');

    if (!cashfreeAppId || !cashfreeSecretKey) {
      throw new Error('Cashfree credentials not configured');
    }

    // Create Cashfree payment order
    const orderId = `ORDER_${enrollment.enrollment_id}_${Date.now()}`;
    const cashfreeOrderRequest = {
      order_id: orderId,
      order_amount: 11700.00,
      order_currency: 'INR',
      customer_details: {
        customer_id: enrollment.id,
        customer_name: enrollmentData.fullName,
        customer_email: enrollmentData.email,
        customer_phone: enrollmentData.mobile,
      },
      order_meta: {
        return_url: `${Deno.env.get('SUPABASE_URL')}/functions/v1/verify-payment?order_id={order_id}`,
        notify_url: `${Deno.env.get('SUPABASE_URL')}/functions/v1/verify-payment`,
      },
    };

    // Call Cashfree API to create order (Production: https://api.cashfree.com/pg/orders, Test: https://sandbox.cashfree.com/pg/orders)
    const cashfreeResponse = await fetch('https://sandbox.cashfree.com/pg/orders', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-version': '2023-08-01',
        'x-client-id': cashfreeAppId,
        'x-client-secret': cashfreeSecretKey,
      },
      body: JSON.stringify(cashfreeOrderRequest),
    });

    if (!cashfreeResponse.ok) {
      const errorText = await cashfreeResponse.text();
      console.error('Cashfree API error:', errorText);
      throw new Error(`Cashfree API error: ${errorText}`);
    }

    const cashfreeOrder = await cashfreeResponse.json();
    console.log('Cashfree order created:', cashfreeOrder);

    // Update enrollment with payment order ID
    await supabase
      .from('enrollments')
      .update({ payment_id: orderId })
      .eq('id', enrollment.id);

    return new Response(
      JSON.stringify({
        success: true,
        enrollmentId: enrollment.enrollment_id,
        paymentSessionId: cashfreeOrder.payment_session_id,
        orderId: orderId,
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    );
  } catch (error: any) {
    console.error('Error in create-payment function:', error);
    return new Response(
      JSON.stringify({ error: error?.message || 'Unknown error occurred' }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500,
      }
    );
  }
});
