import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";

export default function TermsOfUse() {
  return (
    <div className="max-w-4xl mx-auto p-6">
      <div className="mb-6">
        <Button variant="ghost" asChild>
          <Link to="/" className="flex items-center gap-2">
            <ArrowLeft className="h-4 w-4" /> Back to Home
          </Link>
        </Button>
      </div>

      <div className="prose prose-slate max-w-none">
        <h1 className="text-3xl font-bold mb-8">
          Website Usage Terms & Conditions
        </h1>

        <div className="space-y-8">
          <section>
            <p className="text-slate-700">
              This document is an electronic record under the provisions of the
              Information Technology Act, 2000 and the rules made thereunder. It
              is generated by a computer system and does not require any
              physical or digital signature.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">1. General Terms</h2>
            <p className="text-slate-700 mb-4">
              The domain name dos.suncitysolar.in ("Website") is owned and
              operated by M/s Shree Chandramangal Suncity Marketing Private
              Limited, operating its educational division as Discovery of
              Success (DOS) – A Business School of Suncity Solar, a company
              incorporated under the Companies Act, 2013, having its registered
              office at 3rd Floor, Plot No. A-317A, Dr. Rajendra Prasad Nagar,
              Gopalpura Bypass, Mansarovar, Jaipur – 302020 (Rajasthan), India.
            </p>
            <p className="text-slate-700">
              By accessing, browsing, or using this Website in any manner, you
              agree to be bound by these Terms & Conditions ("Terms"). If you do
              not agree to any part of these Terms, you must not use this
              Website or any of its services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">2. Website Access</h2>
            <ul className="list-disc pl-6 space-y-2 text-slate-700">
              <li>
                Access to this Website is provided on a temporary basis. We
                reserve the right to modify, suspend, or withdraw any service
                without prior notice.
              </li>
              <li>
                We shall not be liable if the Website is unavailable at any time
                for any reason.
              </li>
              <li>
                You are responsible for ensuring all technical arrangements
                necessary for accessing the Website.
              </li>
              <li>
                You agree not to use any automated systems or software to
                extract data from this Website for commercial purposes without
                prior written consent.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">
              3. Intellectual Property Rights
            </h2>
            <p className="text-slate-700 mb-4">
              All contents—including text, graphics, logos, images, videos,
              course materials, layout, and code—are protected under the
              Copyright Act 1957 and are the exclusive property of DOS or its
              licensors.
            </p>
            <p className="text-slate-700 mb-4">
              No part of the Website may be reproduced, distributed,
              transmitted, or used for commercial purposes without explicit
              written permission.
            </p>
            <p className="text-slate-700">
              Limited permission is granted to view or print materials for
              personal, non-commercial use only, provided all copyright notices
              remain intact.
            </p>
            <p className="text-slate-700 mt-4">
              Any unauthorized use of our intellectual property may result in
              civil and criminal liability.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">4. Acceptable Use</h2>
            <p className="text-slate-700 mb-4">You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2 text-slate-700">
              <li>
                Use the Website for any unlawful, fraudulent, defamatory, or
                harmful activity.
              </li>
              <li>
                Upload, transmit, or distribute any viruses, malware, or
                malicious software.
              </li>
              <li>
                Attempt to gain unauthorized access to any portion of the
                Website or related systems.
              </li>
              <li>
                Engage in data scraping, mirroring, framing, or use of
                bots/crawlers.
              </li>
              <li>
                Post, publish, or transmit any content that infringes another's
                intellectual property or privacy rights.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">
              5. User Account and Security
            </h2>
            <ul className="list-disc pl-6 space-y-2 text-slate-700">
              <li>
                You must be 18 years or older to create an account or enrol in
                any course.
              </li>
              <li>
                You are solely responsible for maintaining confidentiality of
                your username and password.
              </li>
              <li>
                You shall immediately notify DOS of any unauthorized use of your
                account or security breach.
              </li>
              <li>
                DOS is not responsible for losses resulting from your failure to
                secure account credentials.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">
              6. Course Enrollment and Payment
            </h2>
            <ul className="list-disc pl-6 space-y-2 text-slate-700">
              <li>
                Enrolment in any course constitutes a binding contract to pay
                the prescribed course fee.
              </li>
              <li>
                Fees are non-transferable and non-refundable, except in cases
                specifically allowed under our Refund & Cancellation Policy.
              </li>
              <li>
                DOS reserves the right to revise course fees, modify content, or
                discontinue any program without prior notice.
              </li>
              <li>
                Access to course materials will be granted only after
                confirmation of full payment through authorized gateways.
              </li>
              <li>
                DOS follows secure digital transaction protocols compliant with
                RBI Payment Gateway Guidelines.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">
              7. User Content and Conduct
            </h2>
            <p className="text-slate-700 mb-4">
              Any content submitted by users (reviews, comments, testimonials,
              etc.) must be accurate and non-infringing.
            </p>
            <p className="text-slate-700 mb-4">
              By posting such content, you grant DOS a worldwide, royalty-free,
              perpetual license to use, reproduce, and display the content for
              marketing or educational purposes.
            </p>
            <p className="text-slate-700">
              DOS reserves the right to remove or edit any content that violates
              these Terms or applicable law.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">
              8. Privacy and Data Protection
            </h2>
            <p className="text-slate-700 mb-4">
              All personal data collected through this Website will be handled
              in accordance with our Privacy Policy, compliant with the
              Information Technology (Reasonable Security Practices and
              Procedures and Sensitive Personal Data or Information) Rules 2011.
            </p>
            <p className="text-slate-700 mb-4">
              By using the Website, you consent to such data collection and
              processing for legitimate business purposes.
            </p>
            <p className="text-slate-700">
              DOS implements adequate organizational and technical safeguards to
              prevent unauthorized access, disclosure, or alteration of user
              data.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">
              9. Disclaimer of Warranties
            </h2>
            <p className="text-slate-700 mb-4">
              The Website and all content are provided "as is" and "as
              available" without warranties of any kind, either express or
              implied.
            </p>
            <p className="text-slate-700 mb-4">DOS does not guarantee that:</p>
            <ul className="list-disc pl-6 space-y-1 text-slate-700">
              <li>The Website will be uninterrupted, timely, or error-free;</li>
              <li>
                The information or content will always be accurate, complete, or
                reliable;
              </li>
              <li>Any defects will be corrected promptly.</li>
            </ul>
            <p className="text-slate-700 mt-4">
              Users rely on the information at their own discretion and risk.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">
              10. Limitation of Liability
            </h2>
            <p className="text-slate-700 mb-4">
              To the fullest extent permitted by law, DOS and its affiliates
              shall not be liable for:
            </p>
            <ul className="list-disc pl-6 space-y-1 text-slate-700">
              <li>Any indirect, consequential, or special damages;</li>
              <li>Loss of income, profits, data, or goodwill;</li>
              <li>
                Any business interruption or system failure arising out of use
                or inability to use the Website, even if DOS has been advised of
                the possibility of such damages.
              </li>
            </ul>
            <p className="text-slate-700 mt-4">
              Your sole and exclusive remedy for dissatisfaction with the
              Website or its content is to discontinue using it.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">11. Indemnification</h2>
            <p className="text-slate-700">
              You agree to indemnify and hold harmless DOS, its officers,
              employees, agents, and affiliates from any claims, damages,
              losses, or expenses (including legal fees) arising out of: Your
              breach of these Terms; Your misuse of the Website or violation of
              any applicable law; or Any infringement of third-party rights by
              content submitted through your account.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">
              12. Modification of Terms
            </h2>
            <p className="text-slate-700 mb-4">
              DOS may revise or update these Terms at any time without prior
              notice.
            </p>
            <p className="text-slate-700">
              The revised Terms shall take effect from the date of publication
              on the Website. Users are responsible for reviewing the latest
              version periodically.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">
              13. Termination of Access
            </h2>
            <p className="text-slate-700">
              DOS reserves the right to suspend or terminate user access to the
              Website or any service, without liability, if it reasonably
              believes that the user has violated these Terms or applicable
              laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">
              14. Governing Law and Jurisdiction
            </h2>
            <p className="text-slate-700 mb-4">
              These Terms shall be governed by and construed in accordance with
              the laws of India.
            </p>
            <p className="text-slate-700">
              All disputes arising out of or relating to the use of this Website
              shall be subject to the exclusive jurisdiction of the courts at
              Jaipur, Rajasthan.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">
              15. Contact Information
            </h2>
            <div className="space-y-2 text-slate-700">
              <p>
                For any questions, concerns, or grievance redressal, please
                contact:
              </p>
              <p>Grievance Officer: Mr. Mahipal Singh</p>
              <p>
                Phone:{" "}
                <a
                  href="tel:+917014759495"
                  className="text-blue-600 hover:underline"
                >
                  +91 7014759495
                </a>
              </p>
              <p>
                Email:{" "}
                <a
                  href="mailto:dos@suncitysolar.in"
                  className="text-blue-600 hover:underline"
                >
                  dos@suncitysolar.in
                </a>
              </p>
              <p>
                Address: 3rd Floor, Plot No. A-317A, Dr. Rajendra Prasad Nagar,
                Gopalpura Bypass, Mansarovar, Jaipur – 302020 (Rajasthan),
                India.
              </p>
            </div>
          </section>

          <div className="pt-8 border-t border-slate-200">
            <p className="text-sm text-slate-500">
              Last updated: November 6, 2024
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
