import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";

export default function TermsOfUse() {
  return (
    <div className="max-w-4xl mx-auto p-6">
      <div className="mb-6">
        <Button variant="ghost" asChild>
          <Link to="/" className="flex items-center gap-2">
            <ArrowLeft className="h-4 w-4" /> Back to Home
          </Link>
        </Button>
      </div>

      <div className="prose prose-slate max-w-none">
        <h1 className="text-3xl font-bold mb-8">Website Usage Terms & Conditions</h1>
        
        <div className="space-y-8">
          <section>
            <p className="text-slate-700">
              This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">1. General Terms</h2>
            <p className="text-slate-700 mb-4">
              The domain name www.suncitysolar.in ("Website") is owned by M/s Shree Chandramangal Suncity Marketing Private Limited ("Suncity Solar"), a company incorporated under the Companies Act, with its registered office at 3rd Floor, P.No. A-317A, Dr. Rajendra Prasad Nagar, Gopalpura Bypass, Mansarovar, Jaipur, Rajasthan - 302020, India.
            </p>
            <p className="text-slate-700">
              By accessing or using this website, you agree to be bound by these Terms of Use. If you do not agree with any part of these terms, you must not use this website.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">2. Website Access</h2>
            <ul className="list-disc pl-6 space-y-2 text-slate-700">
              <li>Access to this website is permitted on a temporary basis.</li>
              <li>We reserve the right to withdraw or amend the services without notice.</li>
              <li>We will not be liable if this website is unavailable at any time or for any period.</li>
              <li>You are responsible for making all arrangements necessary for you to have access to our site.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">3. Intellectual Property Rights</h2>
            <p className="text-slate-700 mb-4">
              The content, layout, design, data, databases, and graphics on this website are protected by intellectual property laws and are owned by Suncity Solar or its licensors.
            </p>
            <p className="text-slate-700">
              You may view, download, and print pages from the website for your own personal use, subject to the restrictions set out below and elsewhere in these terms of use.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">4. Acceptable Use</h2>
            <p className="text-slate-700 mb-4">You must not use our website in any way that causes, or may cause, damage to the website or impairment of the availability or accessibility of the website; or in any way which is unlawful, illegal, fraudulent, or harmful.</p>
            <p className="text-slate-700">You must not use our website to copy, store, host, transmit, send, use, publish, or distribute any material which consists of (or is linked to) any spyware, computer virus, or other malicious computer software.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">5. User Account and Security</h2>
            <ul className="list-disc pl-6 space-y-2 text-slate-700">
              <li>You must be at least 18 years of age to use our website.</li>
              <li>You are responsible for maintaining the confidentiality of your account and password.</li>
              <li>You agree to accept responsibility for all activities that occur under your account or password.</li>
              <li>You must notify us immediately of any unauthorized use of your account or any other breach of security.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">6. Course Enrollment and Payment</h2>
            <ul className="list-disc pl-6 space-y-2 text-slate-700">
              <li>By enrolling in our courses, you agree to pay the specified fees.</li>
              <li>All fees are non-refundable except as stated in our Refund Policy.</li>
              <li>We reserve the right to modify course fees at any time without prior notice.</li>
              <li>Access to course materials is granted only after payment confirmation.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">7. Disclaimer of Warranties</h2>
            <p className="text-slate-700 mb-4">
              The information on this website is provided "as is" without any representations or warranties, express or implied. Suncity Solar makes no representations or warranties in relation to this website or the information and materials provided on this website.
            </p>
            <p className="text-slate-700">
              Without prejudice to the generality of the foregoing paragraph, Suncity Solar does not warrant that:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1 text-slate-700">
              <li>This website will be constantly available, or available at all; or</li>
              <li>The information on this website is complete, true, accurate, or non-misleading.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">8. Limitations of Liability</h2>
            <p className="text-slate-700 mb-4">
              Suncity Solar will not be liable to you (whether under the law of contact, the law of torts, or otherwise) in relation to the contents of, or use of, or otherwise in connection with, this website:
            </p>
            <ul className="list-disc pl-6 space-y-1 text-slate-700">
              <li>For any indirect, special, or consequential loss; or</li>
              <li>For any business losses, loss of revenue, income, profits, or anticipated savings, loss of contracts or business relationships, loss of reputation or goodwill, or loss or corruption of information or data.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">9. Indemnity</h2>
            <p className="text-slate-700">
              You hereby indemnify Suncity Solar and undertake to keep Suncity Solar indemnified against any losses, damages, costs, liabilities, and expenses (including without limitation legal expenses and any amounts paid by Suncity Solar to a third party in settlement of a claim or dispute on the advice of Suncity Solar's legal advisers) incurred or suffered by Suncity Solar arising out of any breach by you of any provision of these terms of use.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">10. Changes to Terms</h2>
            <p className="text-slate-700">
              We may revise these terms of use from time to time. Revised terms of use will apply to the use of our website from the date of the publication of the revised terms of use on our website. Please check this page regularly to ensure you are familiar with the current version.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">11. Governing Law</h2>
            <p className="text-slate-700 mb-4">
              These terms and conditions will be governed by and construed in accordance with the laws of India, and any disputes relating to these terms and conditions will be subject to the exclusive jurisdiction of the courts of Jaipur, Rajasthan.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">12. Contact Information</h2>
            <div className="space-y-2 text-slate-700">
              <p>For any questions about these Terms of Use, please contact:</p>
              <p>Email: <a href="mailto:info@suncitysolar.in" className="text-blue-600 hover:underline">info@suncitysolar.in</a></p>
              <p>Grievance Officer: <a href="tel:+919772911700" className="text-blue-600 hover:underline">+91 97729 11700</a></p>
              <p>Address: 3rd Floor, P.No. A-317A, Dr. Rajendra Prasad Nagar, Gopalpura Bypass, Mansarovar, Jaipur, Rajasthan - 302020</p>
            </div>
          </section>

          <div className="pt-8 border-t border-slate-200">
            <p className="text-sm text-slate-500">
              Last updated: November 6, 2024
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
